### ISSUE TITLE
feature: auto closing branches

### ISSUE THREAD

**Issue by dme86** [spreequalle/ebuilds#2]
yo generik,

you can add the following yaml file to your workflows folder for auto-closing branches after PR:
```yaml
name: delete branch on close pr
on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        uses: SvanBoxel/delete-merged-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

cheers,
dan
